# Generated by Django 5.1.2 on 2024-10-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('conteudo', models.TextField(max_length=5000)),
                ('imagem', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
